environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "64"

services:
  - postgresql93

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  #################################
  # Installing postgis
  #################################

  - choco install -y postgis-9.3


  - SET OPENSPENDING_SETTINGS=./test_settings.py
  #################################
  # Download and install Erlang
  #################################

  - echo Downloading Erlang...
  - ps: (new-object System.Net.WebClient).Downloadfile('http://www.erlang.org/download/otp_win32_17.5.exe', 'C:\Users\appveyor\erlang.exe')
  - echo Installing Erlang...
  - start /B /WAIT C:\Users\appveyor\erlang.exe /S /D=C:\Users\appveyor\erlang
  - set ERLANG_HOME=C:\Users\appveyor\erlang

  #################################
  # Download and install RabbitMQ
  #################################

  - echo Downloading Rabbit...
  - ps: (new-object System.Net.WebClient).Downloadfile('https://www.rabbitmq.com/releases/rabbitmq-server/v3.5.2/rabbitmq-server-3.5.2.exe', 'C:\Users\appveyor\rabbit.exe')
  - echo Installing Rabbit...
  - start /B /WAIT C:\Users\appveyor\rabbit.exe /S
  - ps: (Get-Service -Name RabbitMQ).Status

  #################################
  # Install everything else
  #################################
  - pip install -r requirements.txt -e .
  - pip install psycopg2 coveralls


  - psql -c 'create database openspending_testing;' -U postgres
  - psql -d openspending_testing -U postgres -c "create extension postgis"
  - pg_restore -d openspending_testing -U postgres < ./openspending/tests/fixtures/testing_database.backup


build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - nosetests --with-coverage --cover-package=openspending

after_test:
  - coveralls 