DO $$
BEGIN
	RAISE INFO 'CREATE of CATEGORY';

	CREATE TABLE FIND.CATEGORY
	(
		CATEGORY_ID SERIAL,
		DATA_MODIFIED_TS TIMESTAMP NOT NULL,,
		CATEGORY_NAME VARCHAR(200) NOT NULL,
		SUBCATEGORY_NAME VARCHAR(200) NOT NULL,
		CONSTRAINT CATEGORY_PK PRIMARY KEY ( CATEGORY_ID )
	)
	WITH (
		OIDS=FALSE
	);
END $$;
