DO $$
BEGIN
	RAISE INFO 'CREATE of CATEGORY_JUNCTION';

	CREATE TABLE FIND.CATEGORY_JUNCTION
	(
		DATA_MODIFIED_TS TIMESTAMP NOT NULL,
		INDICATOR_ID INT NOT NULL,
		CATEGORY_ID INT NOT NULL,
		CONSTRAINT CATEGORY_JUNCTION_PK PRIMARY KEY ( INDICATOR_ID, CATEGORY_ID )
	)
	WITH (
		OIDS=FALSE
	);
END $$;
