DO $$
BEGIN
	RAISE INFO 'CREATE of COLLECTION';

	CREATE TABLE FIND.COLLECTION
	(
		COLLECTION_ID SERIAL,
		DATA_MODIFIED_TS TIMESTAMP NOT NULL,
		COLLECTION_NAME VARCHAR(100) NOT NULL,
		CONSTRAINT COLLECTION_PK PRIMARY KEY ( COLLECTION_ID )
	)
	WITH (
		OIDS=FALSE
	);
END $$;
