DO $$
BEGIN
	RAISE INFO 'CREATE of COUNTRY';

	CREATE TABLE FIND.COUNTRY
	(
	COUNTRY_ID SERIAL,
	CONTINENT VARCHAR(15) NOT NULL,
    DOD_GROUP VARCHAR(15) NOT NULL,
    DOS_GROUP VARCHAR(50) NOT NULL,
    USAID_GROUP VARCHAR(50) NOT NULL,
    INCOME_GROUP VARCHAR(20) NOT NULL,
    COUNTRY_NAME VARCHAR(100) NOT NULL,
    SUB_COUNTRY_NAME VARCHAR(100) NOT NULL,
    COUNTRY_GEOGRAPHY geometry(MultiPolygon) NOT NULL,
		CONSTRAINT COUNTRY_PK PRIMARY KEY ( COUNTRY_ID )
	)
	WITH (
		OIDS=FALSE
	);
END $$;
