DO $$
BEGIN
	RAISE INFO 'CREATE of COUNTRY ALTNAME LKUP';

	CREATE TABLE FIND.COUNTRY_ALTNAME_LKUP
	(
		COUNTRY_ALTNAME_ID SERIAL,
		COUNTRY_ALTNAME VARCHAR(100),
		COUNTRY_ID INT NOT NULL,
		
		CONSTRAINT COUNTRY_ALTNAME_ID_PK PRIMARY KEY ( COUNTRY_ALTNAME_ID )
	)
	WITH (
		OIDS=FALSE
	);
END $$;
