DO $$
BEGIN
	RAISE INFO 'CREATE of DATA';

	CREATE TABLE FIND.DATA
	(
		DATA_ID SERIAL,
		DATA_MODIFIED_TS TIMESTAMP NOT NULL,
		COUNTRY_ID INT NOT NULL,
		INDICATOR_ID INT NOT NULL,
		YEAR SMALLINT NOT NULL,
		VALUE NUMERIC(2) NOT NULL,
		CONSTRAINT DATA_PK PRIMARY KEY ( DATA_ID )
	)
	WITH (
		OIDS=FALSE
	);
END $$;
