DO $$
BEGIN
	RAISE INFO 'CREATE of INDICATOR';

	CREATE TABLE FIND.INDICATOR
	(
		INDICATOR_ID SERIAL,
		DATA_MODIFIED_TS TIMESTAMP NOT NULL,
		INDICATOR_NAME VARCHAR(200) NOT NULL,
		INDICATOR_URL VARCHAR(520) NOT NULL,
		INDICATOR_DATA_URL VARCHAR(520) NOT NULL,
		DIRECT_INDICATOR_SOURCE VARCHAR(200) NOT NULL,
		ORIGINAL_INDICATOR_SOURCE VARCHAR(200) NOT NULL,
		YEARS VARCHAR(720) NOT NULL,
		UPDATE_CYCLE VARCHAR(200) NOT NULL,
		SCOPE VARCHAR(200) NOT NULL,
		UNITS VARCHAR(200) NOT NULL,
		LAST_SOURCE_UPDATE_TS TIMESTAMP NOT NULL,
		WHEN_TO_UPDATE_TS TIMESTAMP NOT NULL,
		INDICATOR_DEF TEXT,
		CONSTRAINT INDICATOR_PK PRIMARY KEY ( INDICATOR_ID )
	)
	WITH (
		OIDS=FALSE
	);
END $$;
